import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600","800"],
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className="flex flex-col flex-1 items-center justify-center">
          <Navbar />
          <main className="flex flex-col flex-1 items-center justify-center">{children}</main>
          
        </header>
       
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
